workspace:
  base: /go
  path: src/github.com/nathanmalishev/go_api_example

pipeline:
  build:
    image: golang:1.9

    environment:
    - JWT_SECRET=test

    commands:
    - go get
    - go build
    - go test ./... -v

  publish:
    image: plugins/docker
    repo: nathanmalishev/go_api_example
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    when:
      branch: master

services:
  mongo:
    image: mongo
