workspace:
  base: /go
  path: src/github.com/nathanmalishev/go_api_example

pipeline:
  build:
    image: golang:1.9

    environment:
    - JWT_SECRET=test

    commands:
    - go get
    - go build
    - go test ./... -v

  publish:
    image: plugins/docker
    repo: nathanmalishev/go_api_example
    when:
      branch: master
    secrets: [ docker_username, docker_password ]
    tags: 
      - latest

services:
  mongo:
    image: mongo
