workspace:
  base: /go
  path: src/github.com/nathanmalishev/go_api_example

pipeline:
  build:
    image: golang:1.9

    environment:
    - JWT_SECRET=test

    commands:
    - go get
    - go build
    - go test ./... -v


services:
  mongo:
    image: mongo
    ports: '27017:27017'
